### ISSUE TITLE
emborg-overdue does not send letters

### ISSUE THREAD

**Issue by Ingvarhost** [KenKundert/emborg#12]
Hello!
The emborg-overdue does not send letters after completion. The logs do not even show an attempt to send a letter. At the same time, an ordinary emborg always sends letters successfully. 

Config file:
```
default_maintainer = 'backup@localhost'
dumper = 'backup@localhost'
default_max_age = 25 # hours
root = '/mnt/backup_data/borg'
repositories = [    
    dict(host='fs (/)', path='fs/root'),
]
```
Messages for backup@localhost are forwarded to Gmail. 

Emborg-overdue output:
```
HOST: fs (/)
    sentinel file: /mnt/backup_data/borg/fs/root/index.43
    last modified: 2019-08-07T09:41:23.706817+00:00
    since last change: 120.9 hours
    maximum age: 25 hours
    overdue: True
```

**Comment by KenKundert** [comment]
Did you add the -m or --mail flag?

Typically you run it as a cron job using either:
`4 9 * * * ~/dumper/.local/bin/emborg-overdue --mail > ~/dumper/emborg-overdue.out 2>&`
or
`4 9 * * * ~/dumper/.local/bin/emborg-overdue --quiet --mail`

**Comment by Ingvarhost** [comment]
Thanks so much, now everything works great!
