### ISSUE TITLE
Give the option to run all configurations at once

### ISSUE THREAD

**Issue by stefano-b** [KenKundert/emborg#14]
Given multiple configurations on `~/.config/emborg/`, let's call them `home`, `lamp`, `data`, and so on, I think it would be helpful to have an option to run all found configs with a single command.

So, instead of running `emborg -c home && emborg -c lamp && emborg -c data`, maybe one could run `emborg -a` or `emborg --all`, or `emborg` or something similar.

**Comment by KenKundert** [comment]
Give me some time. Let me see if there are any undesirable consequences of doing that.

It probably only makes sense for the create command, and perhaps the overdue command. Right?

**Comment by stefano-b** [comment]
Thank you.

Yes, I was mainly referring to the create command.

Mounting, restoring, and other actions on existing archives should of course be done on a single repository/archive basis.

**Comment by KenKundert** [comment]
I have implemented composite configurations that allow you to run an emborg command on several configurations at once. See https://emborg.readthedocs.io/en/latest/configuring.html#composite-configurations
I just made a fair amount of changes, so I will probably let the code sit for a while before I update pypi.
