### ISSUE TITLE
Add option to mount the most recent archive found in repository

### ISSUE THREAD

**Issue by stefano-b** [KenKundert/emborg#21]
Currently `emborg mount` accepts a `--date` option where you can select a given date and mount the archive(s) found for that particular timeframe.

I think it would be useful to also have an option to mount the most recent archive found in the repository without having to explicitly give a date.

A possible suggestion would be `--last`, `--latest`, or something similar.

Thank you.

**Comment by KenKundert** [comment]
Done. It is on github as version 1.4.2. It will take some time for this enhancement to make its way to pypi.
