### ISSUE TITLE
mount latest - consistency question

### ISSUE THREAD

**Issue by kewlfft** [KenKundert/emborg#22]
There is a new `--latest` option for mounting the latest archive, however by default other commands like `extract` and `manifest` apply to the **latest** archive while `mount` by default mounts **all** archives.
Therefore wouldn't it make more sense that mount by default mounts the latest archive and that `mount --all` mounts all archives? 
Just a question as I may miss some logic behind.

Related to https://github.com/KenKundert/emborg/issues/21#issue-496777862

**Comment by KenKundert** [comment]
Yeah, I struggled with that. I actually fully implemented `--all` before I changed to `--latest`. My reasoning is as follows:

1. Those other commands are slightly different in that in those commands `--all` would not make sense.
2. Making _all_ the default retains backward compatibility.
3. In general I tend to prefer _all_ because I it allows me to find the version I want, so it seems like a better default to me.

On the other hand, I really value a simple use model, and implementing `--all` rather than `--latest` represents the solution of least surprise, so I can go either way with little persuasion. Now that you have seen my reasoning, what would you suggest I do?

**Comment by kewlfft** [comment]
You're the one doing the work, my first reaction would be: do what fit your needs or what you think is best and as long as we can easily adapt it to ours, which is the case here, that's fine. Otherwise to give you my opinion, I think we should stick as close as possible to the _Borg_ CLI logic not to introduce some other logic. Here because _mount_ applies to both repo and archives, both approaches seem acceptable, I need to look more into it.

**Comment by KenKundert** [comment]
I decided to go with --all in an attempt to make emborg consistent with itself. This change was implemented in the latest version (1.4.5).

**Comment by kewlfft** [comment]
That's a legitimate choice as well, thanks for the implementation of this very useful tool!  When do you expect to release it in pypi?

**Comment by KenKundert** [comment]
I think it is ready now. However, it is my habit to wait a week or two so see if any issues pop up.

**Comment by kewlfft** [comment]
That's good practice, I could create an additional dev package in Arch Linux based on the latest github commit depending how active the future developments of the tool will be.

**Comment by KenKundert** [comment]
I just created another version where I cleaned some things up and fixed some small issues. I think it is getting pretty close; I can probably release it anytime.  I wanted to thank you again for your help and your interest.  Emborg is now quite a bit better than it was a few weeks ago. 

No need to create another package. I think this was an unusually large change.

-Ken

**Comment by kewlfft** [comment]
You can thank me for my interest more than for my help as I have not contributed much at all to the code - partly because you were very quick at implementing all the ideas! I hope I can make some useful PR in the future now that I have the structure of the project in mind.
I believe _Emborg_ can become the reference front-end for _Borg_, it is evolving in a very nice way.

**Comment by KenKundert** [comment]
Thanks!
I got impatient, so I have released version 1.5 with all of these changes and have pushed it to pypi. I believe I am done for now.

**Comment by kewlfft** [comment]
Arch Linux package updated https://aur.archlinux.org/packages/emborg/
New version being tested and no issue so far!

**Comment by KenKundert** [comment]
Thank you!
