### ISSUE TITLE
exclude_from to accept lists

### ISSUE THREAD

**Issue by kewlfft** [KenKundert/emborg#24]
Possible enhancement is to have in configuration `exclude_from` accepting list of filenames instead of a single name as _Borg_ accepts several instances of `exclude_from`.

**Comment by KenKundert** [comment]
Whoops. exclude_from is already supported. To see a list of all the supported borg options type: `emborg settings --available`.

-Ken

**Comment by kewlfft** [comment]
yes it exists but it accepts one filename as a parameter (string), it could accept a list of filenames as _Borg_ accepts several instances of it. This is to be able to provide several filenames.

**Comment by KenKundert** [comment]
I have updated the github repository. I believe it issue is resolved.
