### ISSUE TITLE
Add option for "borg check --repair"

### ISSUE THREAD

**Issue by stefano-b** [KenKundert/emborg#25]
Would you consider adding an option for `borg check --repair` as detailed [here](https://borgbackup.readthedocs.io/en/stable/usage/check.html)?

Maybe by using `emborg check --repair` or even `emborg repair`.

Thank you!

**Comment by KenKundert** [comment]
Yeah. I was actually in the process of adding support for it before I realized it was an experimental feature. Then I put it off. Have you used it? If so, can you tell me about your experience with it?

**Comment by stefano-b** [comment]
Just realized that it is experimental, probably you are right to wait.

I just had a problem with a corrupted archive, I tried to use this option but in the end it was a filesystem issue, not really related to Borg.
