### ISSUE TITLE
How to include a subfolder of an excluded folder?

### ISSUE THREAD

**Issue by stefano-b** [KenKundert/emborg#26]
I need to backup a folder which is located inside an excluded folder.
More precisely, I need to backup `~/.cache/evolution/`, while `~/.cache/` is excluded.

This is my current configuration

```python
src_dirs = '''
    ~/
    ~/.cache/evolution/
    /home/shared/
'''.split()   # absolute path to directory to be backed up

excludes = '''
    ~/**/__pycache__
    ~/**/*.pyc
    ~/**/.*.swp
    ~/**/.*.swo
    ~/**/node_modules
    ~/.cache
    ~/.npm
    ~/.pnpm-store
    ~/.local/share/baloo
    ~/.local/share/Trash
    ~/.thumbnails
'''.split()
```

But it does not seem to work. Is it possible to do so? And how?

**Comment by KenKundert** [comment]
Borg has recently implemented that functionality using patterns (see `borg help patterns`). This is an experimental feature in borg, but it has been available for several years, so it is probably pretty stable. I will look into adding support for patterns in emborg. I'll need a little time to consider the interaction between excludes and patterns.

**Comment by stefano-b** [comment]
Thank you, as usual.
I was not aware of the status if this feature directly in Borg.

**Comment by KenKundert** [comment]
I have just unloaded a new version of Emborg that supports Borg patterns. It is version 1.14.5 and currently only available from github.  I think you can get what you want by replacing your src_dirs and excludes specifications with:
```
patterns = '''
    R ~
    R /home/shared
    + ~/.cache/evolution/
    - ~/**/__pycache__
    - ~/**/*.pyc
    - ~/**/.*.swp
    - ~/**/.*.swo
    - ~/**/node_modules
    - ~/.cache
    - ~/.npm
    - ~/.pnpm-store
    - ~/.local/share/baloo
    - ~/.local/share/Trash
    - ~/.thumbnails
'''
```

**Comment by stefano-b** [comment]
Thank you, I'll test this as soon as possible.

**Comment by KenKundert** [comment]
Please let me know when you have had a chance to try out the latest version. I think it is ready to go, but I would feel more comfortable releasing it if a few more people told me that it worked for them without issues.

**Comment by stefano-b** [comment]
I'm sorry for the late answer, I finally had a chance to extensively test this and it just works as expected, without any problem to report.
Thank you again!
