### ISSUE TITLE
Recovery from a remote repository

### ISSUE THREAD

**Issue by Ingvarhost** [KenKundert/emborg#31]
Hello! A small question on restoring from backups. I have several computers from which I backup to my server. In the emborg settings on computers, I specified encryption: 'repokey' and the passphrase. Suppose that one of the computers is completely out of order, i.e. the emborg settings were lost, but I remember the passphrase. How can I access computer backups on the server where the repositories are located?

**Comment by KenKundert** [comment]
If you used repokey, then the key is contained in the repository, so all you need to recover is the path to the repository and the passphrase for the key.
You can recover using only borg using something like:
```
borg extract /path/to/repo::archive files
```
It should ask you for your passphrase and then extract your files. Once you extract your *Emborg* config files, you can use it to help you extracting further files.

Alternately, you can manually reconstruct your emborg settings files. You basically only need a few things, presumably repository, archive or prefix, and passphrase, and you should be good to go.

-Ken

**Comment by Ingvarhost** [comment]
Thank you so much for your help, I checked that everything works exactly as you wrote.
