### ISSUE TITLE
external dependencies

### ISSUE THREAD

**Issue by kewlfft** [KenKundert/emborg#32]
I am a great fan of _emborg_, I have created and maintain the Arch Linux package.
I have noticed the addition of an external dependency to `quantiphy` in the latest version and have therefore created a new package for it.
I just wanted to highlight this makes the installation of _emborg_ dependent to one more "unofficial" package. Not an issue at all, just for your information, dependencies to non-standard python packages is not neutral.
Thanks again for what you are offering with _emborg_ 

_this issue can be closed as it does not require specific action, just fyi._

**Comment by KenKundert** [comment]
Yeah, I know. I thought it was worth it. It is optional, Emborg would still work if one removed the dependency.  QuantiPhy is the thing that formats the file sizes using SI scale factors.  That is important to me.
I really appreciate hearing from you and your work with Arch.
Thanks!
