### ISSUE TITLE
borg command with archive

### ISSUE THREAD

**Issue by kewlfft** [KenKundert/emborg#34]
I often use the `borg` command on the repo using the `@repo` variable, however how can I run a borg command on a particular archive of the repo? I have tried several combinations like `@repo::Monday` without success.

**Comment by KenKundert** [comment]
Sure enough. Sorry about that. I have fixed the issue. The fixed version is now available on github (version 1.16.1).

**Comment by kewlfft** [comment]
Thanks for the quick fix. I am a daily user of _emborg_, great tool!

**Comment by KenKundert** [comment]
You seem to use the tool in a different way than I do, and do find holes I am unaware of.  I really appreciate you reporting them.
