### ISSUE TITLE
Create failing, appears to not be an issue with emborg though

### ISSUE THREAD

**Issue by alexmitchell** [KenKundert/emborg#36]
I attempted to backup my computer this morning with the `emborg create` command, but it failed.
Judging from the error messages (see below), it seems to be an issue with borg on rsync.net's servers which they updated this morning. I'm not sure if there is much you can do from emborg to fix it, but I thought I should let others know. (Or you can correct me if I'm wrong and there is an issue with Emborg)

Here [(log.txt)](https://github.com/KenKundert/emborg/files/4604892/editted-emborg-log.txt) is the output of the create command with the verbose and narrate options. I have removed some things indicated by <<< >>>. The TypeError complaining about the number of arguments has always occurred in the past during successful runs.

**Comment by alexmitchell** [comment]
Turns out it is not a problem with rsync or Emborg. Rsync support gently informed me that I'm using the wrong Borg version. Adding `remote_path = 'borg1'` to the emborg settings file fixes the issue.

**Comment by KenKundert** [comment]
I went through the same confusion. To help others in the future, I have added a small section of the manual where I describe the unique requirements of rsync.net and borgbase.com: [link](https://emborg.readthedocs.io/en/latest/examples.html#rsync-net). Please take a look and let me know if there is anything I missed.

**Comment by alexmitchell** [comment]
I think that looks good.

The only minor recommendation I can think of is to add a reference/link to the examples  (e.g. "Please see the examples section for more information.") on the main page right after you say "One option is rsync.net. Another is BorgBase. I have experience with both, and both seem quite good."
That will hopefully alert new users for emborg and rsync.net that they should pay attention to that section before using emborg.
