### ISSUE TITLE
Multiple repository configuration

### ISSUE THREAD

**Issue by CodeSmolder** [KenKundert/emborg#37]
Hi,

is there already a solution to backup to multiple repositories? E.g. BorgBase and another internal repository?

Kind regards,
Andreas

**Comment by CodeSmolder** [comment]
I found out, that I can use several configurations for multiple repositories. Would it also make sense to allow a list of repositories in the settings file?

**Comment by KenKundert** [comment]
I am not sure what you are asking. Is it that you want to simultaneously back up to two or more repositories? Perhaps a local repository for speed of recovery and a remote repository for protection against a local disaster? If so, you can use [composite configurations](https://emborg.readthedocs.io/en/latest/configuring.html#composite-configurations).

**Comment by CodeSmolder** [comment]
Perfect, that is what I was looking for....thank you very much.

Emborg is really a great tool :)
