### ISSUE TITLE
Allow --list in prune

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/emborg#38]
In my existing borg backup scripts, I like to see the results of a prune. To achieve this, I pass '--list' to the prune command.

Can this option be added to emborg prune also? It's available as an option to create.

**Comment by KenKundert** [comment]
I have updated the prune command to support the --list option. It is available in this github repository (version 1.18.1).  Can you try it out and let me know if it is what you are expecting?

**Comment by adhawkins** [comment]
I'll try to work out how to install directly from github. Currently running inside a docker container using pip.

Thanks

**Comment by KenKundert** [comment]
Let me know if it is too much trouble.  If it is I will upload it to pypi so you can get it with pip.

**Comment by adhawkins** [comment]
Yes, that seems to do what I want. 

I'm using it in a Docker container, installing from pypi, so would be nice if the version there were upgraded.

**Comment by KenKundert** [comment]
I have uploaded the latest version to pypi.  Thanks for the suggestion!
