### ISSUE TITLE
pass '--progress' during emborg create

### ISSUE THREAD

**Issue by connorhodes** [KenKundert/emborg#39]
I would like to pass the '--progress' option to Borg when running `emborg create`. This will allow me to monitor the progress of an Enborg backup (which I usually run interactively.) It would also be cool to have a `show_progress` setting in the config file allowing the user to configure Emborg to always show progress. Basically, I would like the same modification that was done in #28, but for the '--progress' options.

You can find out more about Borg's progress option [here](https://borgbackup.readthedocs.io/en/stable/usage/create.html#description). (I've also quoted the text below.)
> The --progress option shows (from left to right) Original, Compressed and Deduplicated (O, C and D, respectively), then the Number of files (N) processed so far, followed by the currently processed path.

**Comment by KenKundert** [comment]
Okay, good suggestion. I have added it in the version on github.  I have added the --progress command line option on the create command, and the show_progress option in the Emborg settings files.

Please try it out and let me know if it meets your expectations.

**Comment by connorhodes** [comment]
Yes. This is perfect I tested it both with `--progress` and `show_progress = True`.

Thanks for the awesome project!

**Comment by KenKundert** [comment]
I have update emborg in PyPi. New version is 1.20.

Thanks!
