### ISSUE TITLE
How to add a folder with spaces in its name to the pattern list?

### ISSUE THREAD

**Issue by stefanobartoletti** [KenKundert/emborg#50]
Hi, I need to add a folder which has spaces in its name to the pattern of folders to backup.

In example, how can I add `~/.config/My Dir/` to my pattern which i.e. is:

```
patterns = '''
    R ~/Documents
    R ~/Music
    - ~/Documents/work
'''
```

**Comment by KenKundert** [comment]
I believe you would add a path that contains a space in the same way as you would with any other path.  Did you try it?

If it does not work, you could try specifying your patterns as a list of strings rather than a giant string:
```
patterns = [
    "R ~/Documents",
    "R ~/Music",
    "R ~/.config/My Dir",
    "- ~/Documents/work",
]
```

**Comment by stefanobartoletti** [comment]
Thank you, by using brackets and multiple strings it worked
