### ISSUE TITLE
Clearer explanation of "working_dir" and paths?

### ISSUE THREAD

**Issue by DrBrynzo** [KenKundert/emborg#57]
Would it be possible to get a working example (no pun intended) of "working_dir" that isn't a shell expansion (~)? The reason I ask is that I prefer to make my backups using the relative path from the directory above the backup source. Example, if I want to back up my "www" directory I would "cd /var" and backup "www/" or "./www/". However, if I use "working_dir = '/var'" and "src_dirs = 'www'" (or "./www" or "www/") I get "emborg error: www: not found." even though the directory is very plainly there. I've attempted to parse all the language in the docs describing the use of "working_dir" and "src_dirs" and relative vs. absolute paths but clearly I'm missing something. 

Can you provide a documentation sample of how one would back up something like "/var/www" using the relative path of "www" as the base/source folder?

**Comment by KenKundert** [comment]
I think the reason you were having trouble is that there was a bug in the code.  If you can, please try upgrading emborg from the github site. Hopefully that fixes your issue. However, if you still think the documentation needs to be improved, let me know and I will see to it.

**Comment by DrBrynzo** [comment]
Thanks. If there was a bug hopefully that's it. I just used the emborg version from the Alpine Linux 3.14 packages which appears to be "1.21-r1". I see that's indeed older. I was trying to build a custom mod based on a linuxserver.io docker image and they have yet to rebase to a newer version of Alpine for the base image I'm working from. So... derp.

I'll install a newer version on a VM and see if it just magically works and I'll just postpone my VM -> Docker migration or figure something else out. Cheers.
