### ISSUE TITLE
Support for 'borg compact'

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/emborg#59]
I understand that the next release of borg (1.2) separates the 'prune' and 'compact' operations into two commands (running 'prune' just marks which archives are to be deleted, but doesn't actually delete them until 'compact' is run).

Would be worth looking in to how this can be tied in with emborg I think. Presumably a new command that'd detect whether borg 1.2 is being used? Not sure whether it's the server's borg version or the client's that matters. They may well both have to match up.

https://github.com/borgbackup/borg/blob/1.2.0rc1/docs/changes.rst#version-120a2-and-earlier-2019-02-24

**Comment by KenKundert** [comment]
Thanks for the heads up and the link.  I'll start preparing for the change.

**Comment by KenKundert** [comment]
I have added support for the *compact* command, and have added the *compact_after_delete* setting.  If *compact_after_delete* is True, then the *compact* command is run after the *delete* and *prune* commands.  The version on github currently supports these enhancements.

**Comment by KenKundert** [comment]
This feature has been released in v1.31.
