### ISSUE TITLE
Support for borg create --upload-ratelimit in borg 1.2

### ISSUE THREAD

**Issue by whkoh** [KenKundert/emborg#61]
In Borg 1.2, `--remote-ratelimit` has been deprecated in favor of `--upload-ratelimit`. 

`--remote-ratelimit` still works through an alias.

https://github.com/borgbackup/borg/issues/5611

**Comment by KenKundert** [comment]
Thanks for the heads up.  I have added the ``upload_ratelimit`` setting to the version of *Emborg* on GitHub.

**Comment by KenKundert** [comment]
This feature has been released in version 1.31.
