### ISSUE TITLE
Add support for 'recreate'

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/emborg#64]
borg has a 'recreate' command, which allows for rewriting of existing archives. This command isn't present in emborg.

It could be a conscious decision, as recreate is a potentially dangerous action.

**Comment by KenKundert** [comment]
It was not a conscious decision.  I simply never needed it. Shouldn't be difficult to add.

**Comment by KenKundert** [comment]
I am having second thoughts on adding support for this command.  Seems like it would only be used in exceptional situations.  I am thinking this it is best for people to use Emborg's borg command instead:
```
emborg borg recreate @repo::❬archive❭ --recompress --compression zlib,9                        
```

**Comment by adhawkins** [comment]
That's fair enough. I've only ever needed to use it once myself, just noticed that it wasn't present in emborg. No great loss if it's not available.
