### ISSUE TITLE
Optional notifications on successful completion

### ISSUE THREAD

**Issue by Ingvarhost** [KenKundert/emborg#7]
Is it possible to make optional email notifications upon successful completion of a backup?

**Comment by KenKundert** [comment]
You can add something like this to your config file:
`run_after_backup = ['notify-send "backup succeeds"']`

That will only run if there are no errors and it should raise a notification.

**Comment by Ingvarhost** [comment]
Thanks for the idea. As a result, I used the following:
`run_after_backup = ['echo "" | mail -s "Backup succeeds on {host_name}" root@localhost']`
