### ISSUE TITLE
Composite create fails

### ISSUE THREAD

**Issue by Sysnic73** [KenKundert/emborg#70]
First ... thank you for emborg!

From: `configuring.rst`

> You can run all three configurations with:
> 
> `$ emborg -c all create`

```
$ emborg -c all create
emborg error: all: unknown configuration.
    Perhaps you forgot to add it to the ‘configurations’ setting?.
    Choose from: min and max.
```

**Comment by KenKundert** [comment]
Did you add all to your list of defined configurations? 
In the documentation, that was done by adding the following to *configurations*:
```
configurations = 'home lamp data all=home,lamp,data'
                                 ^^^^^^^^^^^^^^^^^^
```

**Comment by Sysnic73** [comment]
Thanks for the quick response.  I missed that in the docs.
