### ISSUE TITLE
Somewhere along the line emborg stopped posting to healthchecks.io

### ISSUE THREAD

**Issue by ekool** [KenKundert/emborg#74]
I had reported an issue and you. made a change to the code and the post body to healthchecks.io contained the info message... now it seems to be gone again and only sends this: python-requests/2.31.0

It was working for a while, but I've upgraded to a newer emborg and it appears to be broken. 

Original ticket here: https://github.com/KenKundert/emborg/issues/43

**Comment by KenKundert** [comment]
Sorry about that.  I believe I have fixed the issue.  I have checked the fixes into the GitHub repository.  Can you download this new version and try it out and let me know if you have any problems.

**Comment by ekool** [comment]
Yes i will try it soon.

**Comment by KenKundert** [comment]
The latest release (1.38) contains a fix to this issue.
