### ISSUE TITLE
Recommended install with new pip limitations

### ISSUE THREAD

**Issue by descendingnerdliness** [KenKundert/emborg#75]
On Debian Trixie and Ubuntu 23, installation using
`pip install --user emborg`
is no longer allowed.
What is the new preferred method of installation?

**Comment by KenKundert** [comment]
I am not a user of Ubuntu or Debian, and am unaware of any new restrictions on the use of pip.  I did a quick web search and found nothing on it.  Can you point me to something that discusses these new restriction.  Or, can you send me the error message that is issued when you try.

Personally I cannot imagine the rationale for such a restriction.  On the whole the web seems to be enamored with virtualenv.  You could try using that.  I use virtualenv in special situations, but I find it awkward to use for packages I use on a daily basis.

**Comment by descendingnerdliness** [comment]
Thanks Ken,

There is a reasonable explanation of the issue here:
(https://www.linuxuprising.com/2023/03/next-debianubuntu-releases-will-likely.html)

The proposed solution is to use virtualenv, but I agree with you that it is undesirable for this. It would probably also be cumbersome with cron.

Would it work to just run it from a directory in /home/user?

**Comment by KenKundert** [comment]
With the latest version (1.38) you can install either the base version, or the Avendesora version, using *pipx*.

`pipx install emborg`

or

`pipx install emborg[avendesora]`

**Comment by descendingnerdliness** [comment]
Great!
Thank you for your help!
