### ISSUE TITLE
Default config uses notify-send which is not mentioned in dependencies or installation instructions

### ISSUE THREAD

**Issue by jjakob** [KenKundert/emborg#77]
I noticed that my scheduled backup was failing with the error "/bin/sh: 1: notify-send: not found". This is printed by emborg because the ssh connection to my borg server was failing and it tries to use "notifier" that defaults to notify-send. It can be changed in the config (and it says it's better to use "notify" e-mail for scheduled backups instead) but that requirement is not listed either in pyproject.toml or in installation instructions. Maybe that could be added to installation instructions and instruct the user to disable "notifier" if they don't have notify-send or are scheduling emborg.

**Comment by KenKundert** [comment]
I have refined the documentation: [notifier](https://emborg.readthedocs.io/en/latest/configuring.html#notifier)

**Comment by jjakob** [comment]
Maybe also add it to these:
[installing.rst](https://github.com/KenKundert/emborg/blob/master/doc/installing.rst)
[configuring.rst](https://github.com/KenKundert/emborg/blob/master/doc/configuring.rst)

**Comment by KenKundert** [comment]
The latest release (1.38) contains a fix to this issue.
