### ISSUE TITLE
Using a local repository without depending on SSH

### ISSUE THREAD

**Issue by dprobinson** [KenKundert/emborg#8]
Firstly, thanks for releasing Emborg!

The documentation at https://github.com/KenKundert/emborg/blob/c9cc1ace8758ad334bb929ae92ed98ee62988c78/doc/index.rst states the following:

> **repository**: This is the location where all of your files are backed up to. It may be on a local file system or it may be remote, in which case it is accessed using ssh.

Which implies SSH is not used for repositories on the local filesystem. However, if I create a repository of the form: `repository = 'mylocalhostname:/backup:/{host_name}-{user_name}-{config_name}'` it still tries to connect over SSH:

```
/backup $ emborg init
The authenticity of host 'mylocalhostname (::1)' can't be established.
ECDSA key fingerprint is SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXX.
Are you sure you want to continue connecting (yes/no)?
```
What's the correct way to tell Emborg to use a local repository, so that it doesn't use SSH? Is there something else that needs to be put in the first field (n.b. "localhost" yields the same problem)?

Depending on making a successful SSH connection via the loopback interface adds a superfluous dependency on SSH, and will break if a user does anything with SSH locally (changes the host keys, disables it, etc). If there's a way to avoid this, that would be great!

**Comment by KenKundert** [comment]
Besides my normal backups to offsite storage, I also run backups on my home directory every 15 minutes that I store locally. I only keep these backups for a day, and they are there in case I accidentally trash a file that I am working on. With this backup I can quickly recover the latest version of the file even if it has changed earlier in the day.To do this, I use the following repository setting:

`repository = '/home/ken/.cache/backups/{user_name}' ` 

Notice that this is just a simple file path. There is no host name specified, and no colon.

So the thing that is causing ssh to be used is the presence of 'mylocalhostname:' at the front of your repository setting. Once you remove that, you will also need to remove the extra colon after backup. Once you do those two things, the repository will be found in /backup on your local machine and ssh will not be used to create it.

**Comment by dprobinson** [comment]
Thanks Ken, that's great. I was going to update the documentation, but you've already done it!
